excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://emmanuel-galindo.github.io
title: Code Bites
email: egalindo@gmail.com
author: emmanuel-galindo
description: Recording the effort...
paginate: 7
google_analytics: 
github_username:  emmanuel-galindo
linkedin_username: emmanuelgalindo

safe: false
paginate_path: "/page:num"
paginate_per_category: true
default_category: "en"

